#!/bin/bash

# Used in dockerfile as CMD
# Sets up secrets.yml and starts the rails application
set -e

if [ "$RAILS_ENV" = 'production' ]; then
echo "Running Container in production mode"

if [ -z "$SECRET_KEY_BASE" ]; then
  echo "env SECRET_KEY_BASE variable not set"
  echo "Generating new random secret, current user-sessions will be lost"
  export SECRET_KEY_BASE=$(rake secret)
fi


cat > ./config/secrets.yml <<'endmsg'
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
endmsg

fi

## When running as rails
if [ "$RAILS_ENV" = 'development' ]; then
  echo "Running Container in developer mode"
  bundle config --delete frozen
  export BUNDLE_PATH='vendor/bundle'
  bundle config path
  # Try and setup the bundle
  {
    bundle
  } || {
    echo "Bundle failed, please fix it manually"
  }
fi

if [ -z "$@" ]; then
  # Automigrate to latest version.
  if [ -z "$NOMIGRATE" ]; then
    bundle exec rake db:migrate
  fi

  exec bundle exec rails server Puma -b 0.0.0.0
else
  exec "$@"
fi
