version: '2'
services:
  app:
    build: .
    image: app:latest
    ports:
    - "3000:3000"
  dev:
    image: app
    ports:
    - "3000:3000"
    volumes:
    - ".:/app"
    environment:
      RAILS_ENV: development
